[tool.poetry]
name = "empds"
version = "0.1.0"
description = "\"Para crear Empleados\""
authors = ["Deby <deby9477@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
